import type { AppBridge } from './ipc';

export const RPC_BRIDGE_METHODS = [
  'getAllSongs',
  'getSong',
  'addSong',
  'updateSong',
  'deleteSong',
  'toggleFavorite',
  'recomputeAllSongDifficulties',
  'saveGameResult',
  'getGameResults',
  'getUserStats',
  'saveTheoryResult',
  'getTheoryResults',
  'getTheoryStats',
  'getPracticeDays',
  'recordPracticeTime',
  'getPracticeStreak',
  'getAllAchievements',
  'unlockAchievement',
  'getTroubleSpots',
  'updateTroubleSpot',
  'getMeasureAccuracyHistory',
  'getRecommendations',
  'getProgressStats',
  'getProgressTopSongs',
  'getAllUnresolvedTroubleSpots',
  'getCustomFingerings',
  'saveCustomFingering',
  'clearCustomFingerings',
  'getAllFolders',
  'createFolder',
  'renameFolder',
  'deleteFolder',
  'moveSongToFolder',
  'getAllPlaylists',
  'createPlaylist',
  'updatePlaylist',
  'deletePlaylist',
  'getPlaylistSongs',
  'addSongToPlaylist',
  'removeSongFromPlaylist',
  'reorderPlaylistSong',
  'bulkDeleteSongs',
  'bulkMoveSongsToFolder',
  'bulkAddTag',
  'bulkRemoveTag',
  'bulkAddToPlaylist',
  'getSetting',
  'setSetting',
  'resetLearningProgress',
  'resetUserData',
] as const satisfies ReadonlyArray<keyof AppBridge>;

export type RpcBridgeMethod = (typeof RPC_BRIDGE_METHODS)[number];

export const RPC_BRIDGE_METHOD_SET = new Set<string>(RPC_BRIDGE_METHODS);
