export interface SoundboardClip {
  id: string;
  label: string;
  shortLabel: string;
  category: 'sparkle' | 'squeak' | 'horn' | 'drum' | 'shuffle' | 'jingle';
  midi: number;
  src: string;
  gainDb: number;
  source: string;
}

export const SOUNDBOARD_CLIPS: SoundboardClip[] = [
  {
    id: 'rubber-squeak',
    label: 'Rubber Squeak',
    shortLabel: 'Squeak',
    category: 'squeak',
    midi: 60,
    src: '/soundboard/squeaker__05_forte_squeezed.mp3',
    gainDb: -3,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'bike-horn',
    label: 'Bike Horn',
    shortLabel: 'Honk',
    category: 'horn',
    midi: 61,
    src: '/soundboard/motor-horn__05_forte_squeezed.mp3',
    gainDb: -4,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'spark-tap',
    label: 'Spark Tap',
    shortLabel: 'Spark',
    category: 'sparkle',
    midi: 62,
    src: '/soundboard/bell-tree__025_forte_struck-singly.mp3',
    gainDb: -4,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'sparkle-sweep',
    label: 'Spark Sweep',
    shortLabel: 'Sweep',
    category: 'sparkle',
    midi: 63,
    src: '/soundboard/bell-tree__long_forte_glissando.mp3',
    gainDb: -4,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'jingle-short',
    label: 'Jingle Tap',
    shortLabel: 'Jingle',
    category: 'jingle',
    midi: 64,
    src: '/soundboard/sleigh-bells__05_mezzo-forte_shaken.mp3',
    gainDb: -5,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'jingle-long',
    label: 'Jingle Trail',
    shortLabel: 'Trail',
    category: 'jingle',
    midi: 65,
    src: '/soundboard/sleigh-bells__long_mezzo-forte_shaken.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'spring-tap',
    label: 'Spring Tap',
    shortLabel: 'Boing',
    category: 'sparkle',
    midi: 66,
    src: '/soundboard/spring-coil__05_mezzo-forte_struck-singly.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'spring-zap',
    label: 'Spring Zap',
    shortLabel: 'Zap',
    category: 'sparkle',
    midi: 67,
    src: '/soundboard/spring-coil__long_forte_glissando.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'slide-whistle',
    label: 'Toot Short',
    shortLabel: 'Toot',
    category: 'horn',
    midi: 68,
    src: '/soundboard/swanee-whistle__05_forte_effect.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'slide-whistle-long',
    label: 'Toot Long',
    shortLabel: 'Whoop',
    category: 'horn',
    midi: 69,
    src: '/soundboard/swanee-whistle__very-long_forte_effect.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'banana-shake',
    label: 'Banana Shake',
    shortLabel: 'Banana',
    category: 'drum',
    midi: 70,
    src: '/soundboard/banana-shaker__long_forte_shaken.mp3',
    gainDb: -7,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'berry-shake',
    label: 'Berry Shake',
    shortLabel: 'Berry',
    category: 'drum',
    midi: 71,
    src: '/soundboard/strawberry-shaker__phrase_mezzo-forte_rhythm.mp3',
    gainDb: -7,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'castanet-click',
    label: 'Clack Tap',
    shortLabel: 'Clack',
    category: 'drum',
    midi: 72,
    src: '/soundboard/castanets__025_mezzo-forte_struck-singly.mp3',
    gainDb: -5,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'castanet-roll',
    label: 'Clack Roll',
    shortLabel: 'Roll',
    category: 'drum',
    midi: 73,
    src: '/soundboard/castanets__long_mezzo-forte_roll.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'ratchet-click',
    label: 'Rattle Tap',
    shortLabel: 'Rattle',
    category: 'shuffle',
    midi: 74,
    src: '/soundboard/ratchet__025_forte_clean.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
  {
    id: 'ratchet-roll',
    label: 'Rattle Roll',
    shortLabel: 'Buzz',
    category: 'shuffle',
    midi: 75,
    src: '/soundboard/ratchet__long_forte_roll.mp3',
    gainDb: -6,
    source: 'Philharmonia Orchestra Sound Samples',
  },
];

export function getSoundboardClipForMidi(midi: number): SoundboardClip | undefined {
  return SOUNDBOARD_CLIPS.find((clip) => clip.midi === midi);
}
